### ISSUE TITLE
 Client doesn't reconnect if agent restarts

### ISSUE THREAD

**Issue by kshimada-calm** [DataDog/datadog-go#210] opened 2021-07-20 23:37 UTC
It's a same issue as issue #54.  We upgraded datadog-go to the latest version v4.8.0+incompatible but we still are experiencing this issue.

When the target DD service gets restarted (and gets a new address) the client library continues to send the metrics blissfully (and without error) to the old ip address where there is no longer a UDP listener to accept them.

**Comment by sblumenthalAtBraze** [comment] 2021-08-03 14:20
I also just noticed this behavior. We have the datadog agent deployed to each node in our kubernetes cluster as a daemonset, and when upgrades were made to the datadog agent, our applications were no longer sending statsd metrics to datadog. Restarting our applications fixed the problem, but is less than ideal.

**Comment by cychoi-moloco** [comment] 2021-08-12 16:36
👍🏼 
I had the same issue that our service running on top of the GKE. Whenever making some changes of datadog through helm, the service couldn't reconnect to the agent without any error. I've already cut a support ticket to the datadog support team, they said, they couldn't see any issue too.

**Comment by hush-hush** [comment] 2021-10-05 12:25
Hi,

With UDP the agent restart should not be an issue. On k8s and agent restart should not change its IP. When doing an upgrade a new pod will be created with a new IP. You should use the node IP instead to solve this issue.

With UDP we have no way of knowing if the agent is still up on the other side.

How do you deploy your Agent ? Are you using UDP or UDS ?

**Comment by sblumenthalAtBraze** [comment] 2021-10-13 14:16
Update here, we are indeed using UDP, and so it should just work.

It appears, in our case, that this is a similar issue to https://github.com/DataDog/dogstatsd-csharp-client/issues/64, which appears to be caused by https://github.com/kubernetes/kubernetes/issues/95258 (I was able to replicate the conntrack behavior to verify this was our issue)

Or, in other words, the issue is on our kubernetes cluster side, not on datadog's side

**Comment by aexvir** [comment] 2021-11-09 08:51
@hush-hush I developed a test service that is able to reproduce this issue over udp, but I don't experience data loss over uds

when I contacted gcp support they confirmed that the k8s upstream fix for the issue mentioned here should be available on gke versions after `1.21.4-gke.2300`, but when testing using gke `1.21.5-gke.1302` I'm still seeing the same issue with missing data over udp 😕 

could be anything else on datadog's side? or it's for sure on k8s/gke's side?

**Comment by hush-hush** [comment] 2021-11-29 13:47
That's great to hear @aexvir, thanks for updating this issue.

I'm going to close it but feel free to reopen it or a new one if needed.

**Closed by hush-hush** 2021-11-29 13:47 UTC

**Comment by louiscb** [comment] 2024-07-09 17:34
I appear to have the same issue occurring on newer versions of the same technologies. On a K8s cluster I am running an application with this library communicating to a Datadog Agent on the same node. I use UDP by setting e.g `statsd.New("HOST_IP:PORT", "prefix")`. When the Datadog Agent restarts the metrics to Datadog stop. 

I am using v5.5.0 of this lib, Cluster's Kubernetes version `v1.28.9-eks` and Dd agent `v7.47.1`. By restarting the application pod the connection works again with the newly restarted Datadog pod. Other non Go services are on the same cluster and don't have this issue.
