### ISSUE TITLE
Events not sent

### ISSUE THREAD

**Issue by omerlh** [DataDog/datadog-go#112] opened 2019-12-05 06:28 UTC
I'm trying to send events using the following code:
```go
r.statasd, err := statsd.New("127.0.0.1:8125")
event := statsd.NewEvent("New version published", 
		fmt.Sprintf("A new version (%d) of %s was deployed to namespace %s, using chart %s. Deploy status - %s", release.Version, release.Name, release.Namespace, release.Chart, status))

	event.Priority = statsd.Normal

	if (status == "DEPLOYED"){
		event.AlertType = statsd.Info
	} else {
		event.AlertType = statsd.Error
	}
	event.Hostname = release.Name

	event.Tags = []string {fmt.Sprintf("namespace:%s", release.Namespace)}

	r.statsd.Event(event)
```
But for some reason, I don't see the event on Datadog, no relevant logs on the local agent or the statsd (which has no logs :(). Agent is running using the following docker command:
```bash
DOCKER_CONTENT_TRUST=1 docker run -d --name dd-agent -v /var/run/docker.sock:/var/run/docker.sock:ro -v /proc/:/host/proc/:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e DD_API_KEY=<> -e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true -p 8125:8125 datadog/agent:latest
```

What am I missing?

**Comment by arbll** [comment] 2019-12-05 08:49
Hi @omerlh,

DogStatsD traffic is sent over UDP, I think you are missing a `/udp` suffix to your port mapping:
`docker run ... -p 8125:8125/udp datadog/agent:latest`.

If you still have issues after that I can help you dig deeper.

**Comment by omerlh** [comment] 2019-12-05 08:58
Hey @arbll, thank you for the quick response :) 
Still not seeing it... Also not seeing any events received on the agent logs:

```
2019-12-05 08:54:18 UTC | CORE | INFO | (cmd/agent/app/run.go:233 in StartAgent) | GUI server port -1 specified: not starting the GUI.
2019-12-05 08:54:18 UTC | CORE | INFO | (pkg/forwarder/forwarder.go:156 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://6-15-1-app.agent.datadoghq.com" (1 api key(s))
2019-12-05 08:54:18 UTC | CORE | INFO | (cmd/agent/app/run.go:273 in StartAgent) | logs-agent disabled
2019-12-05 08:54:18 UTC | CORE | INFO | (pkg/dogstatsd/listeners/udp.go:79 in Listen) | dogstatsd-udp: starting to listen on [::]:8125
2019-12-05 08:54:18 UTC | CORE | INFO | (pkg/tagger/tagger.go:152 in tryCollectors) | docker tag collector successfully started
2019-12-05 08:54:18 UTC | CORE | INFO | (pkg/collector/runner/runner.go:92 in NewRunner) | Runner started with 4 workers.
2019-12-05 08:54:18 UTC | PROCESS | INFO | (main_common.go:106 in runAgent) | running on platform: linux-4.9.184-linuxkit-x86_64-with-debian-10.2
2019-12-05 08:54:18 UTC | PROCESS | INFO | (main_common.go:109 in runAgent) | running version: Version: 6.15.1, Git hash: 44c5066, Git branch: HEAD, Build date: 2019-11-26T22:19:09, Go Version: 1.10.1, 
2019-12-05 08:54:18 UTC | PROCESS | INFO | (pkg/tagger/tagger.go:152 in tryCollectors) | docker tag collector successfully started
2019-12-05 08:54:18 UTC | PROCESS | INFO | (pkg/process/checks/container.go:45 in Init) | no network ID detected: could not detect network ID
2019-12-05 08:54:18 UTC | PROCESS | INFO | (collector.go:116 in run) | Starting process-agent for host=docker-desktop, endpoints=[https://process.datadoghq.com], enabled checks=[container rtcontainer]
2019-12-05 08:54:18 UTC | CORE | INFO | (pkg/collector/python/init.go:284 in Initialize) | Initializing rtloader with python2 /opt/datadog-agent/embedded
2019-12-05 08:54:18 UTC | PROCESS | INFO | (collector.go:101 in runCheck) | Finished container check #1 in 1.1316ms
2019-12-05 08:54:18 UTC | CORE | INFO | (pkg/util/cloudprovider.go:45 in DetectCloudProvider) | No cloud provider detected
2019-12-05 08:54:19 UTC | CORE | INFO | (pkg/collector/python/datadog_agent.go:120 in LogMessage) | - | (ddyaml.py:123) | monkey patching yaml.load...
2019-12-05 08:54:19 UTC | CORE | INFO | (pkg/collector/python/datadog_agent.go:120 in LogMessage) | - | (ddyaml.py:127) | monkey patching yaml.load_all...
2019-12-05 08:54:19 UTC | CORE | INFO | (pkg/collector/python/datadog_agent.go:120 in LogMessage) | - | (ddyaml.py:131) | monkey patching yaml.dump_all... (affects all yaml dump operations)
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/collector.go:57 in NewCollector) | Embedding Python 2.7.17 (default, Nov 26 2019, 22:16:11) [GCC 4.7.2]
2019-12-05 08:54:20 UTC | CORE | INFO | (cmd/agent/common/autoconfig.go:71 in SetupAutoConfig) | Registering docker config provider polled every 1s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/autodiscovery/autoconfig.go:351 in initListenerCandidates) | docker listener successfully started
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/autodiscovery/providers/file.go:72 in Collect) | file: searching for configuration files at: /etc/datadog-agent/conf.d
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/autodiscovery/providers/file.go:72 in Collect) | file: searching for configuration files at: /opt/datadog-agent/bin/agent/dist/conf.d
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/autodiscovery/providers/file.go:76 in Collect) | Skipping, open /opt/datadog-agent/bin/agent/dist/conf.d: no such file or directory
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/autodiscovery/providers/file.go:72 in Collect) | file: searching for configuration files at: 
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/autodiscovery/providers/file.go:76 in Collect) | Skipping, open : no such file or directory
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/collector/python/check.go:201 in Configure) | could not get a 'disk' check instance with the new api: __init__() takes at least 4 arguments (4 given)
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/collector/python/check.go:202 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the constructor
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/collector/python/check.go:217 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_config` function from the 'datadog_agent' package (disk).
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/collector/python/check.go:201 in Configure) | could not get a 'network' check instance with the new api: __init__() takes at least 4 arguments (4 given)
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/collector/python/check.go:202 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the constructor
2019-12-05 08:54:20 UTC | CORE | WARN | (pkg/collector/python/check.go:217 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_config` function from the 'datadog_agent' package (network).
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check cpu with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check disk with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check docker with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check file_handle with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check io with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check load with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check memory with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check network with an interval of 15s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check ntp with an interval of 15m0s
2019-12-05 08:54:20 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check uptime with an interval of 15s
2019-12-05 08:54:21 UTC | CORE | INFO | (pkg/metadata/host/host.go:152 in getNetworkMeta) | could not get network metadata: could not detect network ID
2019-12-05 08:54:21 UTC | CORE | INFO | (pkg/serializer/serializer.go:283 in SendMetadata) | Sent metadata payload, size (raw/compressed): 2657/1192 bytes.
2019-12-05 08:54:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check ntp
2019-12-05 08:54:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check cpu
2019-12-05 08:54:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check cpu
2019-12-05 08:54:22 UTC | CORE | INFO | (pkg/forwarder/transaction.go:193 in Process) | Successfully posted payload to "https://6-15-1-app.agent.datadoghq.com/intake/?api_key=*************************adf3a", the agent will only log transaction success every 500 transactions
2019-12-05 08:54:22 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check ntp
system-probe exited with code 0, disabling
trace-agent exited with code 0, disabling
2019-12-05 08:54:25 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check network
2019-12-05 08:54:25 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check network
2019-12-05 08:54:26 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check load
2019-12-05 08:54:26 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check load
2019-12-05 08:54:27 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check file_handle
2019-12-05 08:54:27 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check file_handle
2019-12-05 08:54:28 UTC | PROCESS | INFO | (collector.go:101 in runCheck) | Finished container check #2 in 396.5203ms
2019-12-05 08:54:28 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check disk
2019-12-05 08:54:28 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check disk
2019-12-05 08:54:32 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check uptime
2019-12-05 08:54:32 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check uptime
2019-12-05 08:54:33 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check memory
2019-12-05 08:54:33 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check memory
2019-12-05 08:54:34 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check io
2019-12-05 08:54:34 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check io
2019-12-05 08:54:35 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check docker
2019-12-05 08:54:36 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check cpu
2019-12-05 08:54:36 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check cpu
2019-12-05 08:54:37 UTC | CORE | WARN | (pkg/config/viper.go:168 in GetStringSlice) | failed to get configuration value for key "process_agent_config.host_ips": unable to cast <nil> of type <nil> to []string
2019-12-05 08:54:37 UTC | CORE | INFO | (pkg/util/docker/host_ip_provider.go:64 in tryProviders) | could not deduce host IP from source config: no hostIPs were configured
2019-12-05 08:54:37 UTC | CORE | INFO | (pkg/util/docker/host_ip_provider.go:64 in tryProviders) | could not deduce host IP from source ec2 metadata endpoint: unable to fetch EC2 API, Get http://169.254.169.254/latest/meta-data/local-ipv4: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2019-12-05 08:54:37 UTC | CORE | WARN | (pkg/util/docker/host_ip_provider.go:32 in GetDockerHostIPs) | could not get host IP
2019-12-05 08:54:38 UTC | PROCESS | INFO | (collector.go:101 in runCheck) | Finished container check #3 in 1.4767ms
2019-12-05 08:54:40 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check network
2019-12-05 08:54:40 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check network
2019-12-05 08:54:40 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check docker
2019-12-05 08:54:41 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check load
2019-12-05 08:54:41 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check load
2019-12-05 08:54:42 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check file_handle
2019-12-05 08:54:42 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check file_handle
2019-12-05 08:54:43 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check disk
2019-12-05 08:54:43 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check disk
2019-12-05 08:54:47 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check uptime
2019-12-05 08:54:47 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check uptime
2019-12-05 08:54:48 UTC | PROCESS | INFO | (collector.go:101 in runCheck) | Finished container check #4 in 31.7944ms
2019-12-05 08:54:48 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check memory
2019-12-05 08:54:48 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check memory
2019-12-05 08:54:49 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check io
2019-12-05 08:54:49 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check io
2019-12-05 08:54:50 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check docker
2019-12-05 08:54:50 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check docker
2019-12-05 08:54:51 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check cpu
2019-12-05 08:54:51 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check cpu
2019-12-05 08:54:55 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check network
2019-12-05 08:54:55 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check network
2019-12-05 08:54:56 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check load
2019-12-05 08:54:56 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check load
2019-12-05 08:54:57 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check file_handle
2019-12-05 08:54:57 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check file_handle
2019-12-05 08:54:58 UTC | PROCESS | INFO | (collector.go:103 in runCheck) | Finished container check #5 in 1.335ms. First 5 check runs finished, next runs will be logged every 20 runs.
2019-12-05 08:54:58 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check disk
2019-12-05 08:54:58 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check disk
2019-12-05 08:55:02 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check uptime
2019-12-05 08:55:02 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check uptime
2019-12-05 08:55:03 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check memory
2019-12-05 08:55:03 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check memory
2019-12-05 08:55:04 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check io
2019-12-05 08:55:04 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check io
2019-12-05 08:55:05 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check docker
2019-12-05 08:55:05 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check docker
2019-12-05 08:55:06 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check cpu
2019-12-05 08:55:06 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check cpu
2019-12-05 08:55:10 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check network
2019-12-05 08:55:10 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check network
2019-12-05 08:55:11 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check load
2019-12-05 08:55:11 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check load
2019-12-05 08:55:12 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check file_handle
2019-12-05 08:55:12 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check file_handle
2019-12-05 08:55:13 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check disk
2019-12-05 08:55:13 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check disk
2019-12-05 08:55:17 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check uptime
2019-12-05 08:55:17 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check uptime
2019-12-05 08:55:18 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check memory
2019-12-05 08:55:18 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check memory
2019-12-05 08:55:19 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check io
2019-12-05 08:55:19 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check io
2019-12-05 08:55:20 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check docker
2019-12-05 08:55:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check docker
2019-12-05 08:55:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check cpu
2019-12-05 08:55:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check cpu
2019-12-05 08:55:25 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check network
2019-12-05 08:55:25 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check network
2019-12-05 08:55:26 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check load
2019-12-05 08:55:26 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check load
2019-12-05 08:55:27 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check file_handle
2019-12-05 08:55:27 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check file_handle
```

**Comment by arbll** [comment] 2019-12-05 09:04
Events won't show up in the logs, it would get too spammy ;). 

Can you run `docker exec <container_id> agent status` and paste the output here ?

**Comment by omerlh** [comment] 2019-12-05 09:16
Yeah, sure:
I can see the aggregator has 3 events - which is the number of events I sent. But under Statsd section I don't see anything...

```
Getting the status from the agent.

===============
Agent (v6.15.1)
===============

  Status date: 2019-12-05 09:14:39.628836 UTC
  Agent start: 2019-12-05 08:54:17.380637 UTC
  Pid: 330
  Go Version: go1.12.9
  Python Version: 2.7.17
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -34.469ms
    System UTC time: 2019-12-05 09:14:39.628836 UTC

  Host Info
  =========
    bootTime: 2019-12-02 21:44:34.000000 UTC
    kernelVersion: 4.9.184-linuxkit
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 10.2
    procs: 68
    uptime: 59h9m47s
    virtualizationRole: guest
    virtualizationSystem: docker

  Hostnames
  =========
    hostname: docker-desktop
    socket-fqdn: 84c59575fa36
    socket-hostname: 84c59575fa36
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: dial tcp 169.254.169.254:80: connect: connection refused

=========
Collector
=========

  Running Checks
  ==============
    
    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 82
      Metric Samples: Last Run: 6, Total: 486
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    disk (2.5.1)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 81
      Metric Samples: Last Run: 210, Total: 17,010
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 64ms
      
    
    docker
    ------
      Instance ID: docker [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/docker.d/conf.yaml.default
      Total Runs: 81
      Metric Samples: Last Run: 396, Total: 32,076
      Events: Last Run: 0, Total: 2
      Service Checks: Last Run: 1, Total: 81
      Average Execution Time : 198ms
      
    
    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 81
      Metric Samples: Last Run: 5, Total: 405
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 81
      Metric Samples: Last Run: 65, Total: 5,220
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      
    
    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 81
      Metric Samples: Last Run: 6, Total: 486
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 81
      Metric Samples: Last Run: 17, Total: 1,377
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    network (1.11.5)
    ----------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 82
      Metric Samples: Last Run: 49, Total: 4,018
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 3ms
      
    
    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 2
      Metric Samples: Last Run: 1, Total: 2
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 2
      Average Execution Time : 301ms
      
    
    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 81
      Metric Samples: Last Run: 1, Total: 81
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 81
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 12
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 174
    TimeseriesV1: 81

  API Keys status
  ===============
    API key ending with adf3a: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - adf3a

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 62,626
  Dogstatsd Metric Sample: 1,188
  Event: 3
  Events Flushed: 3
  Number Of Flushes: 81
  Series Flushed: 52,457
  Service Check: 816
  Service Checks Flushed: 891

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 1,187
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 81,595
  Udp Packet Reading Errors: 0
  Udp Packets: 334
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 
```

**Comment by arbll** [comment] 2019-12-05 09:21
There are some default events generated automatically (agent start, ...).
Can you stop the agent, listen on 8125 with netcat: 
```
netcat -ul 8125
```
and try sending a few events ?

**Comment by omerlh** [comment] 2019-12-05 09:24
I don't see them... Is there a way to debug the SDK? I didn't notice any logger when inspecting the code

**Comment by arbll** [comment] 2019-12-05 09:46
Unfortunately, you can't set a logger right now, that's something I plan to add but have not made up my mind on how to do this properly since the relevant parts are executed asynchronously. 
That said I have doubts it would help that much if the issue is like I suspect with the transport since UDP wouldn't report an error even if no one received the message. 

One last easy thing I can think of, can you run netcat with the following as some implementations require the `-p`:
```
nc -u -l -v -p 8125
```

**Comment by omerlh** [comment] 2019-12-08 07:08
Now I can see data on this port:
```
datadog.dogstatsd.client.packets_sent:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_sent:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_writer:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_writer:0|c|#client:go,transport:udpdatadog.dogstatsd.client.packets_sent:1|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_sent:571|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_writer:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_writer:0|c|#client:go,transport:udpdatadog.dogstatsd.client.packets_sent:1|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_sent:573|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_writer:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_writer:0|c|#client:go,transport:udpdatadog.dogstatsd.client.packets_sent:1|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_sent:573|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_writer:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_writer:0|c|#client:go,transport:udpdat
```

My program does not exist, but it's running inside the reconcile loop of an operator (CoreOS Operator SDK). I also suspected this might be the issue so I added some sleep but it didn't helped...

**Comment by hush-hush** [comment] 2020-04-20 21:24
Hi @omerlh,

Taking over from arbll on this issue. Have you tried flushing the client before exiting the operator's loop ?

calling `client.Flush()` will force write all data to the wire.

**Comment by omerlh** [comment] 2020-04-22 05:49
It's been a while and I kinda stopped working on this project :) If I ever get back to it, I'll try that - thanks!

**Comment by DouglasPuppioPereira** [comment] 2020-07-16 16:56
Hi @hush-hush , I am facing the same issue with mine. Any possible solution?

**Comment by hush-hush** [comment] 2021-03-31 12:45
OK, I'm going to close the issue for now. Feel free to reopen it if needed.

**Closed by hush-hush** 2021-03-31 12:45 UTC
